// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdfnnoqwypstpcmyjgpf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkZm5ub3F3eXBzdHBjbXlqZ3BmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNjkxNTIsImV4cCI6MjA1OTY0NTE1Mn0.lBXcyoRuBIG71pZjPZZyCwotpRyH1qZE4Xm5PuDwsv4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);